[package]
name = "forged-in-lost-lands"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]   
resolver = "2"
members = ["prime-derived", "prime-forge"] 

[dependencies]
prime-forge = { path = "prime-forge" }
prime-derived = { path = "prime-derived" }
nalgebra-glm = "0.18.0"



[[example]]
name = "basic"
path = "examples/basic.rs"